### ISSUE TITLE
can't run it because of "Something went wrong when fetching access token"

### ISSUE THREAD

**Issue by jthadden** [antca/geppetto#1]
I took the session cookie via FF developer console using ctrl+shift+c, Web-Memory, __Secure-next-auth.session-token

When I run
`sudo docker-compose run --rm geppetto`
I just get the html page of ChatGPT back with an error message at the end:
```
error: Uncaught Error: Something went wrong when fetching access token!
      throw new Error("Something went wrong when fetching access token!");
            ^
    at ChatGPT.getAccessToken (file:///app/src/chat_gtp.ts:57:13)
    at async ChatGPT.sendMessage (file:///app/src/chat_gtp.ts:75:25)
    at async Conversation.sendMessage (file:///app/src/chat_gtp.ts:12:43)
    at async Geppetto.handleMessageFromChatGPT (file:///app/src/geppetto.ts:163:22)
    at async file:///app/src/main.ts:53:20
```

Tried with Fedora and Debian/Sid. Any Ideas?

**Comment by jthadden** [comment]
Some fix in the latest version and fortunately it is now possible to use the API key. Unfortunately now I get no reply at all besides empty "geppetto: " prompts.

**Comment by antca** [comment]
For the usage with the cookie, you must copy the whole `Cookie` header:
- Go to https://chat.openai.com/chat using Firefox (chrome may not work)
- Log in to your OpenAI account
- Open the developer tools in Firefox
- Look at one of the requests in the "Network" tab (you may need to reload the page)
- In the `Request Headers` section, locate the `Cookie` header
- Right-click on the `Cookie` header and choose `Copy Value`
- Paste the entire value into your .env file

You may need to repeat these steps periodically, as the cookie may expire.

As for the usage with the API token, it should work as expected. If you encountered any issues, it may have been a temporary problem with the OpenAI API. Keep an eye on the API usage when using this method.

From my experience, using the cookie is faster than using the API token.

I apologize for the delayed response.
